[tool.poetry]
name = "lab6"
version = "0.1.0"
description = ""
authors = ["Kanzu <kanzu32@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
matplotlib = "^3.8.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
